In [1]:
from scipy.stats import ks_2samp

In [2]:
import numpy as np

In [19]:
arr1 = np.arange(10)
arr2 = np.arange(10)

In [6]:
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
arr2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
res = ks_2samp(arr1,arr2)

In [22]:
res.pvalue

1.0

In [10]:
arr1 = np.arange(10)
arr2 = np.arange(10,20)

In [11]:
arr2

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [14]:
res = ks_2samp(arr1,arr2)
res

KstestResult(statistic=1.0, pvalue=1.0825088224469026e-05)

In [15]:
res.pvalue

1.0825088224469026e-05

In [16]:
round(res.pvalue)

0

In [ ]:
NULL hypothesis :  Two dataset are from same distribution
Ailterate hypothesis : Two dataset are not from same distribution

p>0.05 accept the Null hypothesis

if p>0.05 :
    we have suuficient proof that Null hypothesys is True

else:
    we dont have suuficient proof that Null hypothesys is True